site_name: Vault18 Card Catalog
site_url: https://vault18.github.io

extra_css:
  - assets/stylesheets/vault18.css?v={{ build_date }}

theme:
  name: material
  palette:
    - scheme: slate
      primary: purple
      accent: lime
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/vault18-logo.png
  favicon: images/vault18-favicon.png

