site_name: Vault18 Card Catalog
site_url: https://vault18.github.io
theme:
  name: material
  palette:
    primary: purple
    accent: lime
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/vault18-logo.png
  favicon: images/vault18-favicon.png

nav:
  - Home: index.md
  - Magic: 
      - All Cards: mtg/index.md
  - Pokémon:
      - All Cards: pokemon/index.md
  - Yu-Gi-Oh:
      - All Cards: yugioh/index.md
  - Lorcana:
      - All Cards: lorcana/index.md
  - One Piece:
      - All Cards: onepiece/index.md
  - Bulk:
      - All Cards: bulk/index.md

markdown_extensions:
  - tables
  - admonition
  - toc
  - attr_list
